import "./globals.css";
import NavBar from "./components/NavBar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=clash-display@500&display=swap" rel="stylesheet"/>
      </head>
      <body className="bg-black overflow-x-hidden"><NavBar/>{children}</body>
    </html>
  );
}
